# Generated by Django 4.0.3 on 2022-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationNotResidentialBuilding',
            fields=[
                ('calification', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('min_C', models.FloatField()),
                ('max_C', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResidentialBuilding',
            fields=[
                ('calification', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('min_C1', models.FloatField()),
                ('max_C1', models.FloatField()),
                ('min_C2', models.FloatField(null=True)),
                ('max_C2', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingBuldingDemandDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dipersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingBuldingEnergyAndEmissionsDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dipersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewBuldingDemandDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dipersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewBuldingEnergyAndEmissionsDispersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('dipersion', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewBuildingEnergyConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='NewBuildingEmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='NewBuildingDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='ExistingBuildingEnergyConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='ExistingBuildingEmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
                ('ACS', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
        migrations.CreateModel(
            name='ExistingBuildingDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.BooleanField()),
                ('climatic_zone', models.CharField(max_length=4)),
                ('heating_mean', models.FloatField()),
                ('refrigeration', models.FloatField()),
            ],
            options={
                'unique_together': {('building_type', 'climatic_zone')},
            },
        ),
    ]
